const USERS = [
  { id: 1, name: "Aisha Rahman", role: "Designer", city: "London", country: "United Kingdom", status: "active", email: "aisha.r@studio.io" },
  { id: 2, name: "Ben Carter", role: "Engineer", city: "Austin", country: "United States", status: "active", email: "ben.c@devstack.com" },
  { id: 3, name: "Clara Nguyen", role: "Product", city: "Singapore", country: "Singapore", status: "away", email: "clara.n@growth.co" },
  { id: 4, name: "Diego Morales", role: "Engineer", city: "Barcelona", country: "Spain", status: "active", email: "diego.m@kernel.dev" },
  { id: 5, name: "Elena Volkov", role: "Designer", city: "Berlin", country: "Germany", status: "offline", email: "elena.v@pixelhaus.de" },
  { id: 6, name: "Finn O'Brien", role: "Support", city: "Dublin", country: "Ireland", status: "active", email: "finn.o@helpdesk.ie" },
  { id: 7, name: "Grace Kim", role: "Engineer", city: "Seoul", country: "South Korea", status: "active", email: "grace.k@shipfast.kr" },
  { id: 8, name: "Hassan Ali", role: "Product", city: "Dubai", country: "UAE", status: "away", email: "hassan.a@roadmap.ae" },
  { id: 9, name: "Isla Fraser", role: "Designer", city: "Edinburgh", country: "United Kingdom", status: "active", email: "isla.f@craft.scot" },
  { id: 10, name: "Jonas Weber", role: "Engineer", city: "Munich", country: "Germany", status: "offline", email: "jonas.w@buildhaus.de" },
  { id: 11, name: "Keiko Tanaka", role: "Support", city: "Tokyo", country: "Japan", status: "active", email: "keiko.t@care.jp" },
  { id: 12, name: "Liam Brooks", role: "Product", city: "Toronto", country: "Canada", status: "active", email: "liam.b@launch.ca" },
  { id: 13, name: "Maya Patel", role: "Designer", city: "Mumbai", country: "India", status: "away", email: "maya.p@visual.in" },
  { id: 14, name: "Noah Silva", role: "Engineer", city: "São Paulo", country: "Brazil", status: "active", email: "noah.s@runtime.br" },
  { id: 15, name: "Olivia Chen", role: "Support", city: "Vancouver", country: "Canada", status: "offline", email: "olivia.c@assist.ca" },
  { id: 16, name: "Priya Sharma", role: "Engineer", city: "Bangalore", country: "India", status: "active", email: "priya.s@scale.in" },
  { id: 17, name: "Quinn Reed", role: "Product", city: "Portland", country: "United States", status: "active", email: "quinn.r@vision.us" },
  { id: 18, name: "Rafael Costa", role: "Designer", city: "Lisbon", country: "Portugal", status: "away", email: "rafael.c@forma.pt" },
  { id: 19, name: "Sofia Andersson", role: "Engineer", city: "Stockholm", country: "Sweden", status: "active", email: "sofia.a@nordic.dev" },
  { id: 20, name: "Theo Martin", role: "Support", city: "Paris", country: "France", status: "active", email: "theo.m@reply.fr" },
  { id: 21, name: "Uma Desai", role: "Product", city: "Hyderabad", country: "India", status: "offline", email: "uma.d@plan.in" },
  { id: 22, name: "Victor Hale", role: "Engineer", city: "Chicago", country: "United States", status: "active", email: "victor.h@forge.io" },
  { id: 23, name: "Wren Ellis", role: "Designer", city: "Melbourne", country: "Australia", status: "active", email: "wren.e@atelier.au" },
  { id: 24, name: "Xander Wu", role: "Support", city: "Hong Kong", country: "Hong Kong", status: "away", email: "xander.w@desk.hk" },
  { id: 25, name: "Yara Haddad", role: "Engineer", city: "Amman", country: "Jordan", status: "active", email: "yara.h@stack.jo" },
  { id: 26, name: "Zoe Mitchell", role: "Product", city: "Sydney", country: "Australia", status: "active", email: "zoe.m@orbit.au" },
  { id: 27, name: "Ahmed Khan", role: "Engineer", city: "Karachi", country: "Pakistan", status: "active", email: "ahmed.k@dev.pk" },
  { id: 28, name: "Bella Romano", role: "Designer", city: "Milan", country: "Italy", status: "active", email: "bella.r@moda.it" },
  { id: 29, name: "Carlos Vega", role: "Product", city: "Mexico City", country: "Mexico", status: "away", email: "carlos.v@latam.mx" },
  { id: 30, name: "Dana Fischer", role: "Support", city: "Vienna", country: "Austria", status: "active", email: "dana.f@help.at" },
  { id: 31, name: "Emre Yilmaz", role: "Engineer", city: "Istanbul", country: "Turkey", status: "active", email: "emre.y@code.tr" },
  { id: 32, name: "Fatima Noor", role: "Designer", city: "Lahore", country: "Pakistan", status: "away", email: "fatima.n@art.pk" },
  { id: 33, name: "George Papas", role: "Engineer", city: "Athens", country: "Greece", status: "offline", email: "george.p@build.gr" },
  { id: 34, name: "Hana Suzuki", role: "Product", city: "Osaka", country: "Japan", status: "active", email: "hana.s@launch.jp" },
  { id: 35, name: "Ivan Petrov", role: "Engineer", city: "Moscow", country: "Russia", status: "active", email: "ivan.p@stack.ru" },
  { id: 36, name: "Jade Williams", role: "Support", city: "Manchester", country: "United Kingdom", status: "active", email: "jade.w@care.uk" },
  { id: 37, name: "Kofi Mensah", role: "Product", city: "Accra", country: "Ghana", status: "away", email: "kofi.m@growth.gh" },
  { id: 38, name: "Luna Berg", role: "Designer", city: "Copenhagen", country: "Denmark", status: "active", email: "luna.b@forma.dk" },
  { id: 39, name: "Marco Rossi", role: "Engineer", city: "Rome", country: "Italy", status: "active", email: "marco.r@kernel.it" },
  { id: 40, name: "Nadia Hussain", role: "Support", city: "Islamabad", country: "Pakistan", status: "offline", email: "nadia.h@desk.pk" },
  { id: 41, name: "Omar Farouk", role: "Product", city: "Cairo", country: "Egypt", status: "active", email: "omar.f@roadmap.eg" },
  { id: 42, name: "Petra Novak", role: "Designer", city: "Prague", country: "Czech Republic", status: "active", email: "petra.n@pixel.cz" },
  { id: 43, name: "Raj Malhotra", role: "Engineer", city: "Delhi", country: "India", status: "away", email: "raj.m@ship.in" },
  { id: 44, name: "Sara Lindqvist", role: "Support", city: "Oslo", country: "Norway", status: "active", email: "sara.l@reply.no" },
  { id: 45, name: "Tariq Al-Farsi", role: "Engineer", city: "Riyadh", country: "Saudi Arabia", status: "active", email: "tariq.a@forge.sa" },
  { id: 46, name: "Ursula Brandt", role: "Product", city: "Frankfurt", country: "Germany", status: "offline", email: "ursula.b@plan.de" },
  { id: 47, name: "Vera Santos", role: "Designer", city: "Rio de Janeiro", country: "Brazil", status: "active", email: "vera.s@craft.br" },
  { id: 48, name: "Wei Zhang", role: "Engineer", city: "Shanghai", country: "China", status: "active", email: "wei.z@runtime.cn" },
  { id: 49, name: "Yuki Nakamura", role: "Support", city: "Kyoto", country: "Japan", status: "away", email: "yuki.n@care.jp" },
  { id: 50, name: "Zain Malik", role: "Product", city: "Birmingham", country: "United Kingdom", status: "active", email: "zain.m@vision.uk" },
  { id: 51, name: "Anna de Vries", role: "Designer", city: "Amsterdam", country: "Netherlands", status: "active", email: "anna.d@pixel.nl" },
  { id: 52, name: "Lucas Dubois", role: "Engineer", city: "Brussels", country: "Belgium", status: "active", email: "lucas.d@build.be" },
  { id: 53, name: "Nina Keller", role: "Product", city: "Zurich", country: "Switzerland", status: "away", email: "nina.k@plan.ch" },
  { id: 54, name: "Piotr Kowalski", role: "Engineer", city: "Warsaw", country: "Poland", status: "active", email: "piotr.k@stack.pl" },
  { id: 55, name: "Thabo Nkosi", role: "Support", city: "Johannesburg", country: "South Africa", status: "active", email: "thabo.n@care.za" },
  { id: 56, name: "Amara Okafor", role: "Designer", city: "Lagos", country: "Nigeria", status: "active", email: "amara.o@art.ng" },
  { id: 57, name: "James Otieno", role: "Engineer", city: "Nairobi", country: "Kenya", status: "away", email: "james.o@dev.ke" },
  { id: 58, name: "Valentina Rios", role: "Product", city: "Buenos Aires", country: "Argentina", status: "active", email: "valentina.r@launch.ar" },
  { id: 59, name: "Matias Herrera", role: "Engineer", city: "Santiago", country: "Chile", status: "active", email: "matias.h@kernel.cl" },
  { id: 60, name: "Camila Restrepo", role: "Designer", city: "Bogotá", country: "Colombia", status: "offline", email: "camila.r@forma.co" },
  { id: 61, name: "Somchai Boon", role: "Support", city: "Bangkok", country: "Thailand", status: "active", email: "somchai.b@desk.th" },
  { id: 62, name: "Linh Tran", role: "Engineer", city: "Hanoi", country: "Vietnam", status: "active", email: "linh.t@ship.vn" },
  { id: 63, name: "Aisyah Rahman", role: "Product", city: "Kuala Lumpur", country: "Malaysia", status: "away", email: "aisyah.r@growth.my" },
  { id: 64, name: "Budi Santoso", role: "Engineer", city: "Jakarta", country: "Indonesia", status: "active", email: "budi.s@runtime.id" },
  { id: 65, name: "Maria Santos", role: "Designer", city: "Manila", country: "Philippines", status: "active", email: "maria.s@visual.ph" },
  { id: 66, name: "Jack Morrison", role: "Support", city: "Auckland", country: "New Zealand", status: "active", email: "jack.m@help.nz" },
  { id: 67, name: "Reza Karimi", role: "Engineer", city: "Tehran", country: "Iran", status: "offline", email: "reza.k@code.ir" },
  { id: 68, name: "Layla Hosseini", role: "Designer", city: "Baghdad", country: "Iraq", status: "active", email: "layla.h@art.iq" },
  { id: 69, name: "Rahim Ahmed", role: "Product", city: "Dhaka", country: "Bangladesh", status: "active", email: "rahim.a@plan.bd" },
  { id: 70, name: "Sunita Gurung", role: "Support", city: "Kathmandu", country: "Nepal", status: "away", email: "sunita.g@care.np" },
  { id: 71, name: "Dilshan Perera", role: "Engineer", city: "Colombo", country: "Sri Lanka", status: "active", email: "dilshan.p@forge.lk" },
  { id: 72, name: "Chen Wei-Lin", role: "Product", city: "Taipei", country: "Taiwan", status: "active", email: "chen.w@orbit.tw" },
  { id: 73, name: "Olena Shevchenko", role: "Designer", city: "Kyiv", country: "Ukraine", status: "away", email: "olena.s@pixel.ua" },
  { id: 74, name: "Andrei Popescu", role: "Engineer", city: "Bucharest", country: "Romania", status: "active", email: "andrei.p@stack.ro" },
  { id: 75, name: "Zsolt Nagy", role: "Support", city: "Budapest", country: "Hungary", status: "active", email: "zsolt.n@desk.hu" },
  { id: 76, name: "Eero Virtanen", role: "Engineer", city: "Helsinki", country: "Finland", status: "offline", email: "eero.v@build.fi" },
  { id: 77, name: "Sigrid Olafsdottir", role: "Designer", city: "Reykjavik", country: "Iceland", status: "active", email: "sigrid.o@craft.is" },
  { id: 78, name: "Marco Ferreira", role: "Product", city: "Luxembourg", country: "Luxembourg", status: "active", email: "marco.f@launch.lu" },
  { id: 79, name: "Ivana Horvat", role: "Engineer", city: "Zagreb", country: "Croatia", status: "active", email: "ivana.h@kernel.hr" },
  { id: 80, name: "Nikola Jovic", role: "Support", city: "Belgrade", country: "Serbia", status: "away", email: "nikola.j@care.rs" },
  { id: 81, name: "Elena Dimitrova", role: "Designer", city: "Sofia", country: "Bulgaria", status: "active", email: "elena.d@forma.bg" },
  { id: 82, name: "Jorge Quispe", role: "Engineer", city: "Lima", country: "Peru", status: "active", email: "jorge.q@ship.pe" },
  { id: 83, name: "Daniela Vega", role: "Product", city: "Quito", country: "Ecuador", status: "offline", email: "daniela.v@plan.ec" },
  { id: 84, name: "Youssef Benali", role: "Support", city: "Casablanca", country: "Morocco", status: "active", email: "youssef.b@desk.ma" },
  { id: 85, name: "Salma Trabelsi", role: "Designer", city: "Tunis", country: "Tunisia", status: "active", email: "salma.t@art.tn" },
  { id: 86, name: "Moussa Diallo", role: "Engineer", city: "Dakar", country: "Senegal", status: "away", email: "moussa.d@dev.sn" },
  { id: 87, name: "Abebe Tesfaye", role: "Product", city: "Addis Ababa", country: "Ethiopia", status: "active", email: "abebe.t@growth.et" },
  { id: 88, name: "Grace Mwangi", role: "Support", city: "Dar es Salaam", country: "Tanzania", status: "active", email: "grace.m@help.tz" },
  { id: 89, name: "Brian Okello", role: "Engineer", city: "Kampala", country: "Uganda", status: "active", email: "brian.o@forge.ug" },
  { id: 90, name: "Jean-Pierre Nkurunziza", role: "Designer", city: "Kigali", country: "Rwanda", status: "offline", email: "jp.n@visual.rw" },
  { id: 91, name: "Lina Kazakova", role: "Engineer", city: "Almaty", country: "Kazakhstan", status: "active", email: "lina.k@stack.kz" },
  { id: 92, name: "Timur Rakhimov", role: "Product", city: "Tashkent", country: "Uzbekistan", status: "active", email: "timur.r@launch.uz" },
  { id: 93, name: "Narantuya Bat", role: "Support", city: "Ulaanbaatar", country: "Mongolia", status: "away", email: "nara.b@care.mn" },
  { id: 94, name: "Sok Pich", role: "Designer", city: "Phnom Penh", country: "Cambodia", status: "active", email: "sok.p@art.kh" },
  { id: 95, name: "Bounmy Sisavath", role: "Engineer", city: "Vientiane", country: "Laos", status: "active", email: "bounmy.s@build.la" },
  { id: 96, name: "Aung Min", role: "Product", city: "Yangon", country: "Myanmar", status: "offline", email: "aung.m@plan.mm" },
  { id: 97, name: "Faisal Al-Mansouri", role: "Engineer", city: "Doha", country: "Qatar", status: "active", email: "faisal.a@forge.qa" },
  { id: 98, name: "Noor Al-Sabah", role: "Designer", city: "Kuwait City", country: "Kuwait", status: "active", email: "noor.s@pixel.kw" },
  { id: 99, name: "Khalid Al-Harthy", role: "Support", city: "Muscat", country: "Oman", status: "away", email: "khalid.h@desk.om" },
  { id: 100, name: "Sara Bahri", role: "Product", city: "Manama", country: "Bahrain", status: "active", email: "sara.b@roadmap.bh" },
];
